module.exports = {
  content: [
    './*.php',
    './functions.php',
    './app/**/*.php',
    './acf-blocks/**/*.php',
    './acf-blocks/**/*.twig',
    './views/**/*.twig',
  ],
  theme: {
    extend: {
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee linear infinite',
      },
    },
  },
  safelist: [
    'p',
    'pl',
    'pr',
    'py',
    'pt',
    'pb',
    'px',
    'm',
    'ml',
    'mr',
    'mx',
    'mt',
    'mb',
    'my',
    'sm',
    'md',
    'lg',
    'xl',
    'w-full',
    'max-w',
    'max-h',
    'fixed',
    'absolute',
    'relative',
    'inset-0',
    'bg-cover',
    'bg-center',
    'bg-fixed',
    'overflow-hidden',
    'min-h-screen',
    'flex',
    'flex-wrap',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'italic',
    'text-left',
    'text-center',
    'text-right',
    'text-white',
    'text-black',
    'text-gray',
    'text-yellow',
    'z-0',
    'z-10',
    'z-[-10]',
    'bg-black/50',
    'py-8',
    'px-4',
    'pt-12',
    'pb-12',
    'will-change-transform',
    'duration-500',
    'animate-carousel',
    'transition-transform',
    'shadow',
    'rounded',
    'border',
  ],
  plugins: [],
}
