module.exports = {
  content: [
    './*.php',
    './functions.php',
    './app/**/*.php',
    './acf-blocks/**/*.php',
    './acf-blocks/**/*.twig',
    './views/**/*.twig',
  ],
  theme: {
    extend: {
    },
  },
  safelist: [
    'w-full',
    'fixed',
    'absolute',
    'relative',
    'inset-0',
    'bg-cover',
    'bg-center',
    'bg-fixed',
    'overflow-hidden',
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'text-left',
    'text-center',
    'text-right',
    'text-white',
    'text-black',
    'text-gray-200',
    'z-0',
    'z-10',
    'z-[-10]',
    'bg-black/50',
    'py-8',
    'px-4',
    'pt-12',
    'pb-12',
    'will-change-transform',
    'duration-500',
    'animate-carousel',
  ],
  plugins: [],
}
