module.exports = {
  content: [
    './*.php',
    './functions.php',
    './app/**/*.php',
    './acf-blocks/**/*.php',
    './acf-blocks/**/*.twig',
    './views/**/*.twig',
  ],
  theme: {
    extend: {
      spacing: {
        '8': '2rem',
        '4': '1rem',
        '16xl': '4rem',
        '20xl': '5rem',
        '12lg': '3rem',
      },
      zIndex: {
        '1': '1',
        '10': '10',
        '0': '0',
        '-10': '-10',
      },
    },
  },
  safelist: [
    'fixed',
    'absolute',
    'relative',
    'inset-0',
    'bg-cover',
    'bg-center',
    'bg-fixed',
    'overflow-hidden',
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'text-left',
    'text-center',
    'text-right',
    'text-white',
    'text-black',
    'text-gray-200',
    'z-0',
    'z-10',
    'z-[-10]',
    'bg-black/50',
    'py-8',
    'px-4',
    'pt-12',
    'pb-12',
    'will-change-transform',
    'duration-500',
  ],
  plugins: [],
}
