<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group([
        'key' => 'group_amenities_fields',
        'title' => 'Équipements',
        'fields' => [
            [
                'key' => 'field_amenities_block_title',
                'label' => 'Titre',
                'name' => 'title',
                'type' => 'text',
                'required' => 1,
            ],
            [
                'key' => 'field_amenities_block_description',
                'label' => 'Description',
                'name' => 'subtitle',
                'type' => 'textarea',
                'rows' => 3,
                'new_lines' => '',
                'required' => 1,
            ],
            [
                'key' => 'field_amenities_categories',
                'label' => 'Catégories',
                'name' => 'categories',
                'type' => 'repeater',
                'layout' => 'row',
                'collapsed' => 'field_amenities_category_key',
                'button_label' => 'Ajouter une catégorie',
                'sub_fields' => [
                    [
                        'key' => 'field_amenities_category_key',
                        'label' => 'Catégorie',
                        'name' => 'category_key',
                        'type' => 'select',
                        'ui' => 1,
                        'return_format' => 'value',
                        'choices' => [
                            'ideal_stay'          => 'Idéal pour votre séjour',
                            'parking'             => 'Parking',
                            'activities'          => 'Activités',
                            'salle_de_bains'      => 'Salle de bains',
                            'chambre'             => 'Chambre',
                            'vue'                 => 'Vue',
                            'exterieur'           => 'En extérieur',
                            'cuisine'             => 'Cuisine',
                            'equipements_chambre' => 'Équipements en chambre',
                            'coin_salon'          => 'Coin salon',
                            'high_tech'           => 'High-tech',
                            'restauration'        => 'Restauration',
                            'internet'            => 'Internet',
                            'reception'           => 'Réception',
                            'services_nettoyage'  => 'Services de nettoyage',
                            'services_affaires'   => 'Services d’affaires',
                            'securite'            => 'Sécurité',
                            'general'             => 'Général',
                            'accessibilite'       => 'Accessibilité',
                            'bien_etre'           => 'Bien-être',
                            'langues_parlees'     => 'Langues parlées',
                        ],
                    ],
                    [
                        'key'   => 'field_amenities_category_description',
                        'label' => 'Description de la catégorie',
                        'name'  => 'category_description',
                        'type'  => 'textarea',
                        'rows'  => 2,
                        'new_lines' => '',
                    ],
                    [
                        'key' => 'field_amenities_items',
                        'label' => 'Éléments',
                        'name' => 'items',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'button_label' => 'Ajouter un élément',
                        'sub_fields' => [
                            [
                                'key' => 'field_amenities_item_label',
                                'label' => 'Libellé',
                                'name' => 'item_label',
                                'type' => 'text',
                                'required' => 1,
                            ],
                            [
                                'key' => 'field_amenities_item_present',
                                'label' => 'Présent ?',
                                'name' => 'item_present',
                                'type' => 'true_false',
                                'ui' => 1,
                                'default_value' => 1,
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/amenities',
                ],
            ],
        ],
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
    ]);
endif;
